# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a5ddae9537d6de67fa597b5e88d44483a64c8e00ed1655e1eeccb9f55163b18755bb4be843d3c6f009a025762e873f64ee7cf0cb5a72d0f9211f6406c0c64c

test:
  secret_key_base: c4de589b2351269e4a36241dee30b7affbc983e53812119355d69f65fb28fafc98eb8106837a920018b6a21d0e2d83e6fc846c15c92b72a89b7e54bd24ea2b34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
